# Generated by Django 4.2.4 on 2023-09-02 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='descrption',
            new_name='description',
        ),
    ]
